# # Exceptional handling
# sakthi = "Good Boy"

# try:
#     print("First Try")
#     print(5 / 2)
#     print(sakthi)
#     print(5 + "5")

# except ZeroDivisionError:
#     print("Can't divide by zero")

# except NameError:
#     print("Please check your varibale is decalared or not")

# except Exception as error:
#     print("Something went wrong : ", error)

# else:
#     print("No exception occurred")

# finally:
#     print("Finally block executed")

# name = "thilaga"

# try:
#     print(5 + "5")
#     print(name)
#     print(4 / 2)
# except ZeroDivisionError:
#     print("Can't divide by zero")
# except Exception as error:
#     print("Something went wrong : ", error)
# else:
#     print("program executed successfully without any errors")
# finally:
#     print("finally whatever error happened it will execute")
